version: '3'

services:
  nextjs:
    build: .
    container_name: coreyalan-nextjs
    environment:
      - NODE_ENV=production
      - DOCUSEAL_API_KEY=${DOCUSEAL_API_KEY:-your_api_key_here}
    restart: unless-stopped
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.coreyalan.rule=Host(`coreyalan.me`)"
      - "traefik.http.routers.coreyalan.entrypoints=websecure"
      - "traefik.http.routers.coreyalan.tls=true"
      - "traefik.http.routers.coreyalan.tls.certresolver=letsencrypt"
      - "traefik.http.services.coreyalan.loadbalancer.server.port=3000"

networks:
  proxy:
    external: true
