import { z } from 'zod';

export const invoiceNinjaTaskSchema = z.object({
  id: z.string(),
  description: z.string(),
  client_id: z.string(),
  status_id: z.string(),
  is_deleted: z.boolean(),
  archived_at: z.string().optional(),
  created_at: z.string(),
  updated_at: z.string(),
  number: z.string(),
  time_log: z.string().optional(),
  is_running: z.boolean(),
  duration: z.number(),
  custom_value1: z.string().optional(),
  custom_value2: z.string().optional(),
  custom_value3: z.string().optional(),
  custom_value4: z.string().optional(),
});

export const invoiceNinjaTaskStatusSchema = z.object({
  id: z.string(),
  name: z.string(),
  color: z.string(),
  is_deleted: z.boolean(),
  archived_at: z.string().optional(),
  created_at: z.string(),
  updated_at: z.string(),
});

export const invoiceNinjaProjectSchema = z.object({
  id: z.string(),
  name: z.string(),
  client_id: z.string(),
  description: z.string().optional(),
  is_deleted: z.boolean(),
  archived_at: z.string().optional(),
  created_at: z.string(),
  updated_at: z.string(),
  number: z.string(),
  color: z.string().optional(),
  budgeted_hours: z.number().optional(),
  task_rate: z.number().optional(),
  due_date: z.string().optional(),
  private_notes: z.string().optional(),
  public_notes: z.string().optional(),
  custom_value1: z.string().optional(),
  custom_value2: z.string().optional(),
  custom_value3: z.string().optional(),
  custom_value4: z.string().optional(),
  documents: z.array(z.any()).optional(),
  tasks: z.array(invoiceNinjaTaskSchema).optional(),
});

export const invoiceNinjaVendorSchema = z.object({
  id: z.string(),
  name: z.string(),
  website: z.string().url().optional(),
  phone: z.string().optional(),
  email: z.string().email().optional(),
  address1: z.string().optional(),
  address2: z.string().optional(),
  city: z.string().optional(),
  state: z.string().optional(),
  postal_code: z.string().optional(),
  country_id: z.string().optional(),
  is_deleted: z.boolean(),
  archived_at: z.string().optional(),
  created_at: z.string(),
  updated_at: z.string(),
  number: z.string(),
  vat_number: z.string().optional(),
  id_number: z.string().optional(),
  custom_value1: z.string().optional(),
  custom_value2: z.string().optional(),
  custom_value3: z.string().optional(),
  custom_value4: z.string().optional(),
  documents: z.array(z.any()).optional(),
});

export const invoiceNinjaProductSchema = z.object({
  id: z.string(),
  product_key: z.string(),
  notes: z.string().optional(),
  cost: z.number(),
  price: z.number(),
  quantity: z.number(),
  tax_name1: z.string().optional(),
  tax_rate1: z.number().optional(),
  tax_name2: z.string().optional(),
  tax_rate2: z.number().optional(),
  tax_name3: z.string().optional(),
  tax_rate3: z.number().optional(),
  is_deleted: z.boolean(),
  archived_at: z.string().optional(),
  created_at: z.string(),
  updated_at: z.string(),
  custom_value1: z.string().optional(),
  custom_value2: z.string().optional(),
  custom_value3: z.string().optional(),
  custom_value4: z.string().optional(),
  documents: z.array(z.any()).optional(),
});

export const invoiceNinjaExpenseSchema = z.object({
  id: z.string(),
  amount: z.number(),
  vendor_id: z.string(),
  client_id: z.string().optional(),
  category_id: z.string().optional(),
  expense_date: z.string(),
  payment_date: z.string().optional(),
  payment_type_id: z.string().optional(),
  private_notes: z.string().optional(),
  public_notes: z.string().optional(),
  tax_name1: z.string().optional(),
  tax_rate1: z.number().optional(),
  tax_name2: z.string().optional(),
  tax_rate2: z.number().optional(),
  tax_name3: z.string().optional(),
  tax_rate3: z.number().optional(),
  is_deleted: z.boolean(),
  archived_at: z.string().optional(),
  created_at: z.string(),
  updated_at: z.string(),
  number: z.string(),
  custom_value1: z.string().optional(),
  custom_value2: z.string().optional(),
  custom_value3: z.string().optional(),
  custom_value4: z.string().optional(),
  documents: z.array(z.any()).optional(),
});

export const invoiceNinjaUserSchema = z.object({
  id: z.string(),
  first_name: z.string(),
  last_name: z.string(),
  email: z.string().email(),
  phone: z.string().optional(),
  signature: z.string().optional(),
  avatar: z.string().optional(),
  is_deleted: z.boolean(),
  archived_at: z.string().optional(),
  created_at: z.string(),
  updated_at: z.string(),
  custom_value1: z.string().optional(),
  custom_value2: z.string().optional(),
  custom_value3: z.string().optional(),
  custom_value4: z.string().optional(),
  documents: z.array(z.any()).optional(),
  google_2fa_secret: z.string().optional(),
  google_2fa_phone: z.string().optional(),
  is_locked: z.boolean().optional(),
  last_login: z.string().optional(),
  failed_logins: z.number().optional(),
  has_password: z.boolean().optional()
}); 